version: '2.1'
services:
  redis:
    container_name: redis
    image: redis:5.0.5-alpine
    networks:
      - notifications-network
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

networks:
  notifications-network:
    driver: bridge
